sonar.projectKey=annuraagggIIIT_ecommerce
sonar.organization=annuraagggiiit
sonar.projectName=ecommerce

sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/generated/**,**/*.test.ts
sonar.coverage.exclusions=src/index.ts,src/db/**,src/routes/**,src/secrets.ts,src/controllers/**,src/middlewares/auth.ts
sonar.test.inclusions=tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
